### ISSUE TITLE
How about filling in the skeleton?

### ISSUE THREAD

**Issue by jean** [Lombiq/Orchard-Security#1]
I'm curious whether you enabling removing permissions in certain contexts.

**Comment by Piedone** [comment]
I'm not sure what you'd like to know Jean. This module is currently empty; we created it because we wanted to implement some features that we didn't do in the end (yet).

**Comment by jean** [comment]
Ah OK that's pretty much what I wanted to know -- whether this module grew
beyond a skeleton. Thanks!

**Comment by Piedone** [comment]
OK then!
